# Generated by Django 3.2 on 2021-05-01 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='appraisal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(5)], verbose_name='отценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderated',
            field=models.BooleanField(verbose_name='промоделирован ли'),
        ),
    ]
