# Generated by Django 3.2 on 2021-05-01 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210501_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='appraisal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='отценка'),
        ),
    ]
