# Generated by Django 3.2 on 2021-05-01 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
